### PR TITLE
Code style

### PR DESCRIPTION
**Pull request by mancze**
I have noticed mixed and improper indentation in main js file. In addition some inspections were popping up from the PhpStorm/WebStorm I'm using. Mainly they was caused by missing/additional semicolon usage.

In this branch I have added `.editorconfig` which should be helpful to ensure all collaborants will follow same code-style rules. In addition I have fixed the errors marked by inspections so the linter is now happy. I know some semicolons are strictly not required but the usage was inconsistent across the file.

By the way I have preserved the indentation by 2 spaces expect the `manifest.json` file as this seemed to be actual setup of the project. I'm not approving it nor disproving it, just accepting that.

### CODE REVIEW

**Comment by infokiller** [comment]
@mancze thanks for doing this, I'm definitely in favor of consistent formatting!
That said, I also hate manually taking care of formatting, so I usually autoformat with clang-format. I added a `.clang-format` file in 53c2433a659a605e79a6116436a3ec1f55e05b6d and would like to autoformat the existing files. It will cause minor changes from the existing formatting (and still consistent with the settings in `.editorconfig`), but I wanted to verify with you before I do that in case you are working on something (I don't want to make your merge harder).
So, can I autoformat?

**Comment by mancze** [comment]
Yes, you can reformat. I use formatter provided by my IDE but I will try to setup `clang-format` on my Windows machine. Never heard of it before.

**Comment by mancze** [comment]
By the way I have a lot of ideas for improvements but I don't know how to discuss them properly. I don't want to start working on them right away as they might be matter of just my opinion. I would rather agree on them before. What is the recommended approach? Should I open the issue for every idea I have? Issues are the only communication channel which comes into my mind.

**Comment by infokiller** [comment]
Opening issues works for me.

**Pull request merged**
