### PR TITLE
Simple option labels

### PR DESCRIPTION
**Pull request by mancze**
1) I thought labels in options are a bit long and confusing. It was easy to get lost as the word "navigate" was used almost everywhere. I have tried to adjust the labels a little. I hope it is more clear now. What do you think?

2) Also I have reordered some options a little. I consider the search result navigation the most important hence all related shortcuts are now placed at the top. It pushed the page navigation options down.

3) "Open in a new tab" shortcut does not actually mean in a new tab. It is a user preference whether it will be a tab or window. So I named it "Open in a new window/tab" now.

4) I feel that more users will tab-oriented than window-oriented. Therefore I consider the new "Open in a new background tab" shortcut more important than previous "Open in a new window/tab". So I switched their order and swapped the defaults for those. `Ctrl+click` does actually open a link in a new background tab so now keyboard navigation `ctrl+return` is even with it.

### CODE REVIEW

**Comment by infokiller** [comment]
Thanks, looks good overall. Can you please update the README.md and https://github.com/infokiller/google-search-navigator/blob/master/assets/chrome_webstore_description.txt - both the keybindings section and the "﻿New in 0.2.6" section. Also mention that the default behavior of Ctrl+Space/Enter changed to open the tab in the background.

Thanks!

**Comment by mancze** [comment]
Ok, forgot about updating the texts.

Yet now I'm not sure whether it is reasonable to change the default keybindings. I mean - users who saved their settings before will probably have conflict with the new shortcut, right :/?

**Comment by infokiller** [comment]
Yeah, changing the defaults isn't ideal, but I think it's reasonable in this case. I expect the number of users that will be affected negatively to be small, and the fix should be straightforward.

**Comment by mancze** [comment]
Alright. I thought about migrations, but I don't think there is some out-of-the-box solution for this. We can excuse it by saying this is just not even v1.0 so BC might happen :).

**Pull request merged**
