### PR TITLE
Initialize javascript package (yarn, gulp)

### PR DESCRIPTION
**Pull request by mancze**
I don't like `keymaster.min.js` being part of the repository as:

* it is a dependency and dependencies should be declared properly,
* it is a processed source file and such files shouldn't be part of the repository either.

So I would like to make this repository healthier and open for future extending. To do so I propose declaring proper `project.json` file making this a regular javascript (`npm`, `yarn`) package. This will make positive impact in many ways.

Following has changed:

* sources moved to the `src` directory not to mix with other files,
* miscellaneous assets moved to the `assets` directory,
* added yarn `project.json`,
* prepared the gulp deployment of the extension files.
* updated the `README.md` with the dev and build instructions.

The workflow is aimed to be fully automated but what is not included in the branch is the actual packing of the extension. The "build" step only prepares sources for testing/packing. This is intentional and I think it should be dealt with separately (in another branch).

In the readme file I chose `yarn` over `npm` but I think the package should be compatible with both managers.

### CODE REVIEW

**Comment by infokiller** [comment]
Awesome and very welcome improvements, thanks a lot for doing this!

Side note: not sure if I already mentioned it or not, but with all the contributions you've already made, you should get at least as much credit as me. So:
1. I sent you an invitation to be a "collaborator" for this project, which should give you broader capabilities in this repo.
2. You're more than welcome to give yourself credit in the README file.

**Comment by infokiller** [comment]
Also, I totally agree about `keymaster.min.js`.
At some point I'd like to explore removing this dependency or replacing it with another library.

**Comment by infokiller** [comment]
@mancze I have a question: should the icons also be in the `assets` dir instead of `src`?

**Comment by mancze** [comment]
No, they shouldn't. The icons are part of the actual packed extension but the files in `assets` directory are just auxiliary files for the project. They are not bundled with the extension. Perhaps I have just wrongly named the directory and in such case feel free to pick another name for it.

**Comment by infokiller** [comment]
IMO ideally there would be a separation between the source files and the build output. This will make it clearer when there are source file transformations, such as adding an id for firefox so that options sync will work when doing development.
This also means that the build scripts will need to explicitly copy the icons from the `assets` dir to the build output directory.
That said, this is not critical at all, and we can do that later.

WDYT?

**Comment by mancze** [comment]
I consider the icons as part of the sources. When talking about sources I do not include only code, but everything what makes up the complete app/package.

I do not have prior experience with frontend/javascript packages so structure I have proposed shouldn't be considered as a dogma :). Feel free to adjust.

I based it on my previous web development experience and also tried to do some swift research. I checked few other packages and in addition what web extension [boilerplate frameworks](https://github.com/bfred-it/Awesome-WebExtensions#boilerplates) come with. The current structure is an attempt to meet the community standard.

I did not structure files in the `src`. There are 10 files. I'm totally fine with that number, no need to structure them for now. In case extension grew big I would tend to stick to following schema (only add directories as needed):

```
├───assets
│   ├───.web-extension-id (in .gitignore)
│   └───chrome-key.pem (in .gitignore)
├───src
│   ├───(s)css
│   ├───images
│   │   └───icon*.png
│   ├───js
│   │   └───google_keyboard_shortcuts.js (main.js)
│   └───mainfest.json
├───tests
├───tools
├───.editorconfig
├───.gitattributes
└───.gitignore
```

And by the way thank you for making me a collaborator of the project. Yet I will stick to the standard PR scheme to merge a proposed changes. It would be awesome if you kept reviewing them even though I can merge them by myself.

**Comment by infokiller** [comment]
Got it, thanks for explaining.
And yes, I'm happy to review future PRs.

**Pull request merged**
