### PR TITLE
Firefox porting

### PR DESCRIPTION
**Pull request by mancze**
I would like to get things moving with #13.

I have reworked my original branch since the changes already made in master was mostly incompatible with my original modifications. So I have dropped the former branch and only cherry-picked the necessary commits. My branch already contains prepared shell script to build a Firefox extension using a `web-ext`.

I would like to ask @infokiller who will be the maintainer/author of the extension on the AMO portal? I'm expecting this to be you but if you want to delegate, just say.

### CODE REVIEW

**Comment by infokiller** [comment]
Changes look good, thanks for doing this!
Re maintainer- I'm not really familiar with the AMO portal, but I assume it would be me in order to have control on the releases in chrome and firefox.

**Comment by infokiller** [comment]
@mancze is there a way to support options sync?

**Comment by mancze** [comment]
Hey, I have not released any AMO extension either :).

The option sync will work if the extension is deployed with the extension id. I have wrote something about it in #13. To summarize:

**Production**

The fully built and signed extension (`.xpi`) has always its id. The `web-ext` will generate id automatically when no id is present in the manifest file. Sync will work automatically after extension is signed for distribution. This is the extension to distribute.

**Development**

You might want to test the option sync during development (unpacked extension). There is the only option: to have extension id present in the `manifest.json` file: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications. Such manifest is incompatible with the Chrome. So its clumsy to test.

**But** I'm already preparing the project to be able to handle these cases smoothly. That assumes we have proper build tools. I'm working on the [mancze/yarn-gulp](/mancze/google-search-navigator/tree/yarn-gulp) branch which introduced proper project layout and especially the `package.json` file along with the dependency and build system management.

**Comment by infokiller** [comment]
Sounds good @mancze 
Should I already try to do a first release for Firefox?

**Comment by mancze** [comment]
Yup, it would be great. I'm already using (private) package built by myself.

**Comment by ecogit** [comment]
fyi - Jacob Chafik recently optionally added Vim-style navigation to his [Google Search Result Shortcuts](https://addons.mozilla.org/en-US/firefox/addon/google-search-result-shortcuts/) extension. It seems to be working fine. 

However, I would prefer to use a unified solution for both Chrome and Firefox, hence [Google Search Navigator](https://github.com/infokiller/google-search-navigator) would cut it. 

In China we would say 加油 (jiāyóu = keep going, literally to "add oil"). Thank you Infokiller & community for your efforts!

**Pull request merged**
